language: node_js
sudo: required
node: 
matrix:
  include:
  - os: osx
  - os: linux
node_js:
- '7'
before_install:
- openssl aes-256-cbc -K $encrypted_85c0316e8199_key -iv $encrypted_85c0316e8199_iv
  -in Certificates.p12.enc -out Certificates.p12 -d
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends
  -y icnsutils graphicsmagick xz-utils; fi
addons:
  apt:
    packages:
    - xvfb
before_script:
- node --version
- npm install
- npm install -g electron
- node --version
- npm run package-ci
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
install:
- nvm install 7
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
dist: trusty
env:
  global:
  - secure: DhjfzKeGf6asGsrjqB/xb8zCXCXz4CudkV/rvGbOacG5yFq5p1YCsvMpi3rGkmbNefyd1NR9YGoQjkhHakhlAUAcIR8EdrAB3/iHX0XTF+mCrNA6Bows/am/molXKG6ODD1AuRAUo902aThuC+JkmNSSc66iW6SMtllLyJ3iC39WZu4Y/y7dkhsyt3RIKga3Q2EpMLWvX6HUdeQbWg1VltniNjWQs4g93WQiNa0eu7YNfpDlEk+/IvFN39wQZi68BToRcE3Py6xgyUKaGf+1wMecKIIw1DLOdafFJbjoPe3Uhg3J0iOuvnEo7bFlcrLTs1UL31j3vhnT7e2s8so6f+CegVRMUOAVH/cDQJOVEjqqPMHJqSTy+lgn1dYIu1cuIELKEitiQ5aUQUpYrjRP4C2Q44NQBrob1fPhdt6DOUqpDkmQd5ME0uevpZi/7ZDNUe279ejh3e1dCTNwkotOBB2Y/DCSI4A7msgRj3UMoUhK9MI6ZorNpxBctSd2X21BkwNX6AurUE0u25aWju4netIcv3DyUveFL8OeVF04gDFaG8bKXfxXwHnNePuLZ7zI3W/B2b5DkGf3EWIm/cThGPim8ietsQtVEHe63OmwRg/x3vnOEIxvMbsU8OUH6ZGnoz2rsE/KH89hYdN0+zxnaO92R/+Kaud/W8jrq7SV8CY=
  - secure: sMlKihc14UjBkw5afdu0YWDeO9MbksiRAcwNA+XI4aUhTMMNw0L2R/N54lovmYLFf7XAjMp+ObsFnGkZ2GY4kF1+0+egnmURLGKj3AN+BYsho0023lzfEXpvmeasoqgd9JmzaWwY4kal4AixnILY8Wgawk7UxzRoPqB4fFuCenbg4RuGa36ZvHt6yTlyGzaBgNUlul9bgvhbM44DalnE0dqeKwm/k3ShWW6pADMR2TtSlSZJgnbJbfFphMAE0fmX1/xt3eVTiqSaW3iximw6WPOQgy+kw4b/X2JxoQISi5itcdmJ0PKdN0s7/etRWBJvR7ljqpfIES839tdUa0QSf3+K/a04ODVseuQ0pdWajP6e4ZOSrARPvsnJcUYeMUbpoqtaocAyDY3frGAEXS/iXPrxsQWKxRzCr0gbYYTtraE4/vf5myEyqX5RdyiV7Buz1RONLji++6Rq31KQMpirEKan0piIi8HfNK+APRdW3/j8Qhoa/449+kWu1GACzDaco8EkRfD1wtT3uRlxqv5Fk/b+MVOt6UtsTDqUuNyeYxvW9DOuWdxMy+uwQIlO3UYRfBIZA9FCgwVYgp8VNH1L+dHkFQh14KOv0tX9eYTRRYjw/h3i5XiGumHDJtwjUqKeGO+88/0WKcpjbcd5lGWwf701dv6I4J1KC3e38cGi2Wk=
  - secure: Mxt7MNvS143zkuYNF8+n12krjgYhTkaihFp4SYGK2LZ4m0eqfu/YOjyJe930dK3xgRqhfcSeEVL63pwlkVOWFdCLZV1c82V3XquyvvCDTYNHxDu7+tCHq+cbit9TmDxnh15Lq9qdX37rxANdUTPWs+FBd/dQxAo8wCz/RrOTVohBd+EcwWi2383z4PM+kVQ8DO6aVhFGl8QLIjaTFj/CGLu4snsRVqyd3TW9B6LjyMnZFbXxF2sorLH8jVD4Ry4yQhQp+2WjR39wAXbihISaGvpWE/fW0UWk5ttnEBKx3wNYk9QktPX6rz5esGP21OnnxNUzqUUOmkR0yWCiIJq/JC7dF6YSqGvenpJOisFKo7mf0XcbtuSoBua5ESX7f63iXh+SeEvYQIaABBmSR9bUnhUW9CEoVfL8jxFjJNJWa2vTuEueLdckIz4opgO1n/ChSp+4Bu2ZO3otNtHP9eiylLfbo5KxlM7o/KNBfXin7uFMqMeP4fHE53XqIMqz4gnUz3LwDNlwvVf2I5TnYIY+uQse41LBXD0mqyEserHAz2yHqugM3T1oc/cUnyr7QJnwdy7eggFHVYE+sZ1GYr44X2pnqZ0AWocIZEWaURM9l1GARF3OhE7k2wy59eFT/fRTu2KZqb8ZOcibYsFRBCOmA5er/gxvrKIRSy3OIHvcEjM=
