language: c
sudo: required
node: 
matrix:
  include:
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
node_js:
- '7'
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends
  -y icnsutils graphicsmagick xz-utils; fi
addons:
  apt:
    packages:
    - xvfb
before_script:
- node --version
- npm install
- npm install -g electron
- node --version
- npm run package || true
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
script:
- npm run e2e
install:
- nvm install 7
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
dist: trusty
deploy:
  provider: releases
  skip_cleanup: true
  api_key: e5895ad1ddd5ef7d4b70aca01164cfeea88f3617
  file:
  - "/release/linux-unpacked/appium-desktop"
  on:
    tags: true
  api_key:
    secure: k2z1kRLa4NTG7yKClQPUvihJH7Ev7xowAJ7G4eRer97Wr8wlktF3J5021EpCk89Hd37w8Wg55CtQg7pkylq5Qz1rMJb9JGFHxNOiP/I/8ai9Uw/yME57yhkCeabhs9iBcJW+9KNaoNZWsGVe+mL4LpF/zZHYCNLGekiRPS4Oa0iSSDyFsb2y0EYidOxWA9LUpI+f+yxJSSxEX6dxlGsFs2vkuDoBtCMgPtfSWyHvP/HdcwKKu2kr+kX8PR8MeZ4KjIFs+gYEEEIkFgd1grZJ9cA/2IfZXO82Gg96tVxeJ917j1OdSNLcnHjjvKcwbNLE1DB17BZ7zATEOWUD6uQc7lpn+W7Gj2djynaaFmI3goPg8Ko4gLduOIbxHlB0G4lGRw5ddWS8TOSvHWmFhp/MyD8L+ks+IGNKrDHXCFo82H/fTJ4Uk4tEXO5rIsdJsQIichxqrXvaBlGPNbzo9+bUZmYJe1G0WkIjdes/yqqr2rY04ISlXLStfMtONzqIpLaycQZ7QSDBl9w16/Ubd1J7Av1pcQce5xNZiHij4sQaeq5+LC4IGC81GkZiK8WUJ0FhJQm334W9ioIdN+yFhajLPqHNrkaFDbbMLBgYPxs4bkhx4VkWkztPFhHfiVDcvSjzBnvRIpkUQL2Q2K7HCJnfZv0sbbD+AjjKoSJGF682qwE=
